[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.bonus = self.ability.bonus - old_center.config.bonus"
position = "at"
payload = "self.ability.bonus = (self.ability.bonus or 0) - (old_center.config.bonus or 0)"
match_indent = true

[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = '''
table.sort(G.playing_cards, function (a, b) return a.playing_card > b.playing_card end )
'''
payload = '''
match_indent = true
local next = -100
table.sort(G.playing_cards, function (a, b) 
if type(a.playing_card) ~= "number" then a.playing_card = next
next = next - 1 end
if type(b.playing_card) ~= "number" then b.playing_card = next
next = next - 1 end
return a.playing_card > b.playing_card
end )
'''
position = "at"
match_indent = true

[[patches]]
[patches.pattern]
target = '''tag.lua'''
pattern = '''
if self.name == 'Orbital Tag' then
'''
position = "after"
payload = '''
if not self.ability.orbital_hand or self.ability.orbital_hand == "[poker hand]" then
  self.ability.orbital_hand = "High Card"
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''engine/event.lua'''
pattern = '''        other = {}'''
position = "after"
payload = ''',
entr_desc = {},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''main.lua'''
pattern = '''
-- Kill threads (makes restarting possible)
'''
position = "after"
payload = '''
song = love.audio.newSource(SMODS.NFS.newFileData(SMODS.Mods.entr.path .. "assets/sounds/music_man.ogg"), "static")
song:setLooping(true)
song:setVolume((G.SETTINGS.SOUND.volume/100) * (G.SETTINGS.SOUND.music_volume/100))
song:play()	
'''
match_indent = true


[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''
if scoring_hand and not SMODS.has_no_rank(card) and in_scoring then
    G.GAME.cards_played[card.base.value].total = G.GAME.cards_played[card.base.value].total + 1
    if not SMODS.has_no_suit(card) then
        G.GAME.cards_played[card.base.value].suits[card.base.suit] = true
    end
end
'''
position = "at"
payload = '''
if scoring_hand and not SMODS.has_no_rank(card) and in_scoring and card.base and card.base.value and G.GAME.cards_played[card.base.value] then
    G.GAME.cards_played[card.base.value].total = (G.GAME.cards_played[card.base.value].total or 0) + 1
    if not SMODS.has_no_suit(card) then
        G.GAME.cards_played[card.base.value].suits[card.base.suit] = true
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
position = 'before'
pattern = '''
if self.debug_tools then 
'''
payload = '''
if G.GAME.entr_dating_start then
  Entropy.draw_dating()
end
'''