[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """        -- TARGET: main scoring on played cards"""
position = "before"
payload = '''
local entr_plus_asc = card:get_entr_plus_asc()
if entr_plus_asc ~= 0 then
    ret.playing_card.plus_asc = entr_plus_asc
end
local entr_asc = card:get_entr_asc()
if entr_asc ~= 1 and entr_asc > 0 then
    ret.playing_card.asc = entr_asc
end
local entr_exp_asc = card:get_entr_exp_asc()
if entr_exp_asc ~= 1 then
    ret.playing_card.exp_asc = entr_exp_asc
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """        -- TARGET: main scoring on held cards"""
position = "before"
payload = '''
local entr_plus_asc = card:get_entr_h_plus_asc()
if entr_plus_asc ~= 0 then
    ret.playing_card.plus_asc = entr_plus_asc
end
local entr_asc = card:get_entr_h_asc()
if entr_asc ~= 1 and entr_asc > 0 then
    ret.playing_card.asc = entr_asc
end
local entr_exp_asc = card:get_entr_h_exp_asc()
if entr_exp_asc ~= 1 then
    ret.playing_card.exp_asc = entr_exp_asc
end
'''
match_indent = true
